[package]
name = "celestial_body_sim"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.15.0", features = ["exr", "webp"] }
clap = { version = "4.5.23", features = ["derive"] }
serde = "1.0.215"
serde_json = "1.0.133"

[profile.release]
opt-level = 3